### PR TITLE
Just fixing the code block in the readme

### PR DESCRIPTION
**Pull request by lucasprag**
Hi.

I liked of the project and I'm studying it, so I found this little issues to fix.

Thank you =)

### CODE REVIEW

**Comment by Lucasosf** [comment]
May you could check please? @alexgraul @iros Thanks

**Comment by Lucasosf** [comment]
Guys? @iros @alexgraul

**Review by alexgraul — APPROVED** [review]

**Comment by iros** [comment]
thanks!

**Comment by lucasprag** [comment]
Thanks =)

**Pull request merged**
